name: Integration Tests (macOS)

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    integration-tests:
        uses: ./.github/workflows/_integration-tests.yml
        with:
            os: macos-latest
